### PR TITLE
do not extract delegate from message before sending?

### PR DESCRIPTION
**Pull request by The-Alchemist**
I'm trying to figure out what the purpose of this code is, because I'm getting:

```
java.lang.AbstractMethodError: com.mockrunner.mock.jms.MockObjectMessage.getBody(Ljava/lang/Class;)Ljava/lang/Object;
    at com.github.thealchemist.fileimport.FilePollerBeanTest$1.onMessage(FilePollerBeanIT.java:40)
    at com.mockrunner.mock.jms.MockMessageConsumer.receiveMessage(MockMessageConsumer.java:86)
    at com.mockrunner.mock.jms.MockQueue.addMessage(MockQueue.java:58)
    at com.mockrunner.mock.jms.MockMessageProducer.send(MockMessageProducer.java:85)
    at com.mockrunner.mock.jms.MockMessageProducer.send(MockMessageProducer.java:53)
    at com.mockrunner.mock.jms.MockQueueSender.send(MockQueueSender.java:25)
    at com.melowe.jms2.compat.Jms2Producer$1.execute(Jms2Producer.java:93)
    at com.melowe.jms2.compat.Jms2Producer$1.execute(Jms2Producer.java:51)
    at com.melowe.jms2.compat.Jms2Util.execute(Jms2Util.java:113)
    at com.melowe.jms2.compat.Jms2Producer.send(Jms2Producer.java:51)
    at com.melowe.jms2.compat.Jms2Producer.send(Jms2Producer.java:126)
```

I'm sending an `ObjectMessage` on one send, and on the receiving end, I'm trying to use {{getBody()}} to extract the contents:

``` java

    @Inject
    private JMSTestModule jmsTestModule;

    @Test
    public void testReceivingMessage() throws Exception {
        /*
         * register a listener for the queue so we can make sure the EJB sends a message
         */
        this.jmsTestModule.registerTestMessageListenerForQueue("queue/fileImport", new MessageListener() {

            @Override
            public void onMessage(Message message) {
                try {
                    Whatever whatever = message.getBody(Whatever.class);
                    assertNotNull(whatever);
                } catch (JMSException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        /*
         * when
         */
        filePoller.sendMessage(new Whatever());

    }
```

Any tips on a workaround would be greatly appreciated.

### CODE REVIEW

**Comment by melowe** [comment]
The message you're getting from the onMessage arg is a JMS 1.\* Message which should be wrapped with a JMS2 one so that the getBody method (JMS2) is implemented. There's am adaptor class that wraps your message listener when thet are registered with the JMSConsumer. You'll need to wrap you're message listener with the adaptor objects so your Message listenr is given a JMS2 Message

**Comment by melowe** [comment]
The adaptor class is Jms2MessageListener  so you'd need to 

```
    this.jmsTestModule.registerTestMessageListenerForQueue("queue/fileImport", new Jms2MessageListener( new MessageListener() {

        @Override
        public void onMessage(Message message) {
            try {
                Whatever whatever = message.getBody(Whatever.class);
                assertNotNull(whatever);
            } catch (JMSException e) {
                throw new RuntimeException(e);
            }
        }
    }));
```

**Comment by melowe** [comment]
I'm not sure if this will work as i don't know what JMSTestModule is. I'll take a look when i get home later.

**Comment by melowe** [comment]
I took a look at the mockrunner JMSTestModule .. the error your getting is expected as mock runner implements JMS 1.\* not 2.0 . This will only show up during runtime as the 2.0 is backward compatible. In fact a lot of the tests i've written are checking for errors that wont show up during compilation.

**Comment by The-Alchemist** [comment]
I tried to subclass `JMSTestModule` to override its methods and have them return your JMS 2.x classes, but I wasn't successful (method return signatures are too "strict").

I think `JMSTestModule`'s biggest help is its `verify`\* methods, which are super convenient for unit tests.

What do you think is the best way forward?  A `JMS2TestModule`?

**Comment by melowe** [comment]
yes i doubt subclassing will work, but wrapping/composing something around the module might work.. Just expose the methods you're interested in and make sure any methods that create jms objects use the JMS2 versions. I've always wished that mock runner objects (sessions etc) had better verify methods that check all child object rather than having to fish through all the indexed connections etc.. Just a total sum of all commit and rollback  counts.

**Comment by melowe** [comment]
I took a look at JMSTestModule i don't see an easy way of doing what you're trying to do.. However more generally i like the idea of a mock jms implementation like mock runner but hides the indexed sessions and connections. I used mock runner for this project as its a JMS 1.\* implementation i could test against.

**Pull request closed without merging**
